# Generated by Django 3.0.1 on 2022-01-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.BooleanField(default=False),
        ),
    ]
